### ISSUE TITLE
release长进度条虽然有用但太沙雕了。还有就是不能打包成一个独立的exe以防止后人篡改

### ISSUE THREAD

**Issue by mmmahhhhe** [GT-ZhangAcer/QPT#5]

**Comment by GT-ZhangAcer** [comment]
1. 终端进度条可以在打包时指定hidden参数为True，这样就是个GUI版本的进度条了，后续会往WPF风格优化。
2. 独立EXE在ToDo.MD文件中，有计划进行，但现阶段版本仍以兼容性为主，未来将在正式版中推出独立EXE。
